name: my-site

services:
  web:
    build: ./backend
    container_name: flask_app
    restart: always
    image: web_backend:${BACKEND_TAG:-latest}
    expose:
      - "5000"

  nginx:
    image: dockerhub.timeweb.cloud/nginx:alpine
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web

