events {
  worker_connections 1024;
}

http {
  server {
    listen 80;
    server_name localhost;

    location / {
      # web - это имя сервиса в docker-compose.yaml
      proxy_pass http://web:5000;

      # forward real clients headers
      proxy_set_header Host $host;      
      proxy_set_header X-Real-IP $remote_addr;      
    }
  }
}
